In [1]:
#Importamos librerias
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler, StandardScaler, LabelEncoder

import warnings
warnings.filterwarnings('ignore')

In [2]:
dataset_completo_url = "Tablon_clientes.csv"

In [3]:
df = pd.read_csv(
    dataset_completo_url,
    sep=';',
    index_col=0
)

In [6]:
#LLamados
df.head()

,GENERO,EDAD,NSE,ESTADOCIVIL,DEPARTAMENTO,RENTA,USO_SMS,DEUDA_ANT,MIN_CALLCENTER,ANTIGUEDAD,USO_MB,DEUDA_ACT,USO_APP,CHURN,MIN_TOT_3M
CLIENT_ID,,,,,,,,,,,,,,,
0,F,80,1,S,LIMA,49.047829,49.689196,50.259706,48.384797,70.0,49.034758,48.833764,NaN,0,100
1,M,26,1,C,LIMA,49.884485,49.126422,49.968794,51.132655,73.0,47.901566,48.864555,NaN,1,97
2,F,35,1,NaN,LIMA,49.674159,49.008166,48.994351,47.206821,69.0,50.561100,52.411366,NaN,1,98
3,M,30,1,V,LIMA,50.971497,NaN,50.074096,47.980931,69.0,49.279711,NaN,NaN,0,100
4,F,65,1,NaN,LIMA,52.313414,50.962695,49.619874,46.892785,49.0,51.430192,NaN,NaN,0,99

In [19]:
df.describe()

,EDAD,NSE,RENTA,USO_SMS,DEUDA_ANT,MIN_CALLCENTER,ANTIGUEDAD,USO_MB,DEUDA_ACT,USO_APP,CHURN,MIN_TOT_3M
count,4997.000000,4997.0,4997.000000,4938.000000,4967.000000,4942.000000,4364.000000,4997.000000,4873.000000,2404.000000,4997.000000,4997.000000
mean,40.367020,1.0,49.920460,49.996233,50.002322,49.648676,58.770852,49.664046,52.100426,50.934384,0.668001,99.329398
std,15.021341,0.0,4.162126,0.999000,1.003869,1.931749,9.666747,1.670653,147.138083,1.941698,0.470978,2.386067
min,5.000000,1.0,-140.000000,46.154745,46.433099,42.182816,30.000000,43.882448,46.710618,44.721870,0.000000,88.000000
25%,28.000000,1.0,48.787983,49.319983,49.336476,48.324646,50.000000,48.473757,49.298500,49.741090,0.000000,98.000000
50%,40.000000,1.0,49.948368,49.979600,50.015584,49.599311,53.000000,49.649429,50.008242,50.737098,1.000000,100.000000
75%,53.000000,1.0,51.147116,50.671762,50.688129,50.954613,69.000000,50.876590,50.670771,52.207674,1.000000,101.000000
max,130.000000,1.0,55.868670,53.895572,53.146460,56.371546,73.000000,55.867741,10321.000000,60.880871,1.000000,108.000000

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4997 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   GENERO          4947 non-null   object
 1   EDAD            4997 non-null   int64
 2   NSE             4997 non-null   int64
 3   ESTADOCIVIL     178 non-null    object
 4   DEPARTAMENTO    4997 non-null   object
 5   RENTA           4997 non-null   float64
 6   USO_SMS         4938 non-null   float64
 7   DEUDA_ANT       4967 non-null   float64
 8   MIN_CALLCENTER  4942 non-null   float64
 9   ANTIGUEDAD      4364 non-null   float64
 10  USO_MB          4997 non-null   float64
 11  DEUDA_ACT       4873 non-null   float64
 12  USO_APP         2404 non-null   float64
 13  CHURN           4997 non-null   int64
 14  MIN_TOT_3M      4997 non-null   int64
dtypes: float64(8), int64(4), object(3)
memory usage: 624.6+ KB

In [22]:
df.shape

(4997, 15)

In [23]:
#contar valores nulos por columnas
df.isnull().sum()

GENERO              50
EDAD                 0
NSE                  0
ESTADOCIVIL       4819
DEPARTAMENTO         0
RENTA                0
USO_SMS             59
DEUDA_ANT           30
MIN_CALLCENTER      55
ANTIGUEDAD         633
USO_MB               0
DEUDA_ACT          124
USO_APP           2593
CHURN                0
MIN_TOT_3M           0
dtype: int64

In [38]:
df["EDAD"].unique()

array([ 80,  26,  35,  30,  65,  31,  61,  22,  56,  64,  25,  44,  52,
        58,  20,  53,  36,  24,  16,  15,  40,  34,  45,  55,  50,  60,
        57,  18,  63,  41,  46,  48,  19,  49,  51,  38,  47,  27,  23,
        21,  32,  59,  39,  29,  62,  17,  33,  54,  42,  43,  37,  28,
       130,   5,   6])

In [7]:
df.map()

TypeError: DataFrame.map() missing 1 required positional argument: 'func'